convidados = ["mãe", "pai", "irmão"]
print(convidados[0].title() + ", Vamos jantar?")
print(convidados[1].title() + ", Vamos jantar?")
print(convidados[2].title() + ", Vamos jantar?")
print("\nMeu "+ convidados[2]+ " não vai poder comparecer, porque surgiu um imprevisto.\n")
convidados[2] = "vó"
print(convidados[0].title() + ", Vamos jantar?")
print(convidados[1].title() + ", Vamos jantar?")
print(convidados[2].title() + ", Vamos jantar?\n")
print(convidados[0].title() +", "+ convidados[1].title() +" e "+ convidados[2].title()+", encontrei uma mesa maior, poderei convidar mais 3 pessoas!" )
convidados.insert(0, "Vô")
convidados.insert(2, "tia")
convidados.append("tio")
print(convidados)
print(convidados[0].title() + ", Vamos jantar?")
print(convidados[1].title() + ", Vamos jantar?")
print(convidados[2].title() + ", Vamos jantar?")
print(convidados[3].title() + ", Vamos jantar?")
print(convidados[4].title() + ", Vamos jantar?")
print(convidados[5].title() + ", Vamos jantar?")